CREATE TABLE
	transactions (
		id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
		--remote INTEGER NOT NULL,
		creation_date DATETIME NOT NULL DEFAULT (NOW ()),
		last_update DATETIME NOT NULL DEFAULT (NOW ()),
		date DATE NOT NULL DEFAULT (NOW ()),
		user INTEGER NOT NULL,
		amount DECIMAL(13, 2) NOT NULL DEFAULT (0.00),
		concept INTEGER NOT NULL
	);